//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderPlacer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMaster
    {
        public ItemMaster()
        {
            this.OrderMasters = new HashSet<OrderMaster>();
        }
    
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public int UnitPrice { get; set; }
        public int AvailableQuantity { get; set; }
    
        public virtual ICollection<OrderMaster> OrderMasters { get; set; }
    }
}
