//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderProcessor.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CompanyEntities1 : DbContext
    {
        public CompanyEntities1()
            : base("name=CompanyEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CustomerMaster> CustomerMasters { get; set; }
        public DbSet<ItemMaster> ItemMasters { get; set; }
        public DbSet<OrderMaster> OrderMasters { get; set; }
        public DbSet<ProcessOrder> ProcessOrders { get; set; }
    }
}
