//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderProcessor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMaster
    {
        public CustomerMaster()
        {
            this.OrderMasters = new HashSet<OrderMaster>();
            this.ProcessOrders = new HashSet<ProcessOrder>();
        }
    
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Email { get; set; }
        public string ContactNo { get; set; }
    
        public virtual ICollection<OrderMaster> OrderMasters { get; set; }
        public virtual ICollection<ProcessOrder> ProcessOrders { get; set; }
    }
}
