//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderProcessor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessOrder
    {
        public int OrderProcessId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string OrderStatus { get; set; }
    
        public virtual CustomerMaster CustomerMaster { get; set; }
        public virtual ItemMaster ItemMaster { get; set; }
        public virtual OrderMaster OrderMaster { get; set; }
    }
}
